version: '3'
services:
  nginx:
    ports:
      - "$APP_DEV_PORT:80"
    volumes:
      - ./nginx/html:/usr/share/nginx/html
  db:
    ports:
      - "$PG_DEV_PORT:5432"
    volumes:
      - pgdata_test:/var/lib/postgresql/data
      - ./data/db:/data
  web:
    ports:
      - "$WEB_DEV_PORT:8080"
  postgrest:
    ports:
      - "$POSTGREST_DEV_PORT:3000"